---
title: "Transcribing Audio with transcribeR"
author: "Christopher Lucas, Shiv Sunil, Thomas Scanlan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
# Abstract

This vignette demonstrates how to use the transcribeR package in R. The transcribeR package is built to request and receive transcriptions from HP IDOL OnDemand's Speech Recognition API.

# Introduction

## Overview

The transcribeR package allows a user to send all WAV files in a specified directory to HP IDOL OnDemand's Speech Recognition API by using the `sendAudioGetJobs` function. The same function stores a list of the Job IDs returned by HP into a CSV file. Once all the WAV files are posted to HP, the transcripts can be extracted with the `retrieveText` function and stored in the same CSV.

## Dependencies

The transcribeR package has the following dependencies:

* httr (R package)

* HP IDOL OnDemand Speech Recognition API Key

# HP IDOL OnDemand's Speech Recognition API

## Overview

HP IDOL OnDemand's Speech Recognition API is trained to transcribe both audio files and video files of human speech. It can work with both local audio and video files and video files available from a URL. The transcription time of the video depends on the length and the segmentation of the video, and it can take anywhere from 0.05 to 0.20 seconds per second of video.

## Calling Asynchronous

Because the transcription process takes a nontrivial amount of time to complete, the POST (posting a file to the API) and GET (retrieving the resulting JSON object, the object that contains the status/output) requests cannot be completed simulatneously, so the output isn't immediately available. Instead, HP IDOL OnDemand provides a Job ID for tracking the status of the call, and connection with the API does not need to be maintained. When the call is complete, the status also returns the transcription.

## API Key

In order to use the Speech Recognition API, one must have an API Key. An API Key can be obtained by making an account at [HP IDOL OnDemand's Website](<https://www.idolondemand.com/signup.html>). API Keys are passed as parameters to the functions `sendAudioGetJobs` and `retrieveText`.

## Job IDs

The Speech Recognition API keeps track of requests by assigning each one a Job ID, so as long as the request has a Job ID, then the job status and transcript could be retrieved at any time. The transcribeR package not only uses Job IDs to retrieve the status, but the function `sendAudioGetJobs` checks to see if a file already has a Job ID on the transcribeR CSV. If it finds one, then it avoids posting the file to HP to minimize upload time and usage.

## Language Codes

When posting to the Speech Recognition API, a language code must be specified. The default in `sendAudioGetJobs` is "en-US", but other languages may be specified. In order to examine which languages are supported, the `printLanguages` function can be utilized to list all the language codes to the user.

## Segmentation

A parameter in `sendAudioGetJobs` named `interval` specifies segmentation length for transcripts in milliseconds. Specifying segment length risks segmenting the audio during an utterance or spoken word. An argument of -1 indicates that the entire file should be transcribed at once (hence no segmentation), and an argument 0 indicates segmentation by each word, which are determined by periods of silence.

## Usage Quotas

HP IDOL OnDemand provides monthly quotas for using its APIs. When a file is posted to the Speech Recognition API, HP IDOL OnDemand subtracts a call and the data of the audio file from its monthly quota. The quotas can be found at <https://www.idolondemand.com/account/quotas.html>. Some relevant ones as of July 22, 2015 are listed below:

* Monthly API Calls (50000)

* Total Input Bytes (30000 MB Source Data)

# transcribeR CSVs

The `transcribeR` package reads and writes CSVs which have the following columns (in order and verbatim):

* DATE

* APIKEY

* FILENAME

* LANGUAGE

* JOBID

* TRANSCRIPT

DATE records the date when the file was posted to the Speech Recognition API. APIKEY records the APIKEY used to make the request. FILENAME is the filepath of the posted file; the `sendAudioGetJobs` function relies on reading the FILENAME field to determine if a file was previously posted so that it will avoid posting it again. LANGUAGE is the associated language code. JOBID is the Job ID returned by the API when the file is posted. TRANSCRIPT is the transcript retrieved from the API once `retrieveText` when the job's status is "finished""; if the job's status is not "finished", then the current status is written to the TRANSCRIPT field. If and only if the TRANSCRIPT field for a file is either `NULL` or a status that isn't "finished", then `retrieveText` will update the field.

# The sendAudioGetJobs() Function

The `sendAudioGetJobs` function handles the POST request to the Speech Recognition API. It accepts the following parameters:

* wav.dir -- the directory in which the WAV files of interest are located

* api.key -- the API Key used to authenticate requests made to HP Idol OnDemand

* interval (defaults to "-1") -- the segmentation interval used by the Speech Recognition API

* encode (defaults to "multipart") -- the format used when posting the file to the Speech Recognition API

* existing.csv (defaults to NULL) -- a CSV that `sendAudioGetJobs` will append to rather than overwrite; if NULL, it will create a new CSV specified by csv.location

* csv.location -- the path of the output file when a new CSV is to be created

* language (defaults to "en-US") -- the language code used by HP

* verbose (defaults to FALSE) -- prints the uploading progress to the user

While it examines all WAV files in wav.dir, it only posts the files that are not also found in an existing CSV.

# The retrieveText() Function



# Examples

Coming soon!